#!/bin/bash

############ Test ##################
mkdir -p /opt/stack/CI-tools

echo "#!/bin/bash" > /opt/stack/CI-tools/CI-test
echo "echo \"blah blah\" ">> CI-test
chmod 775 CI-test
##############################



#if git --version &> /dev/null ; then
    apt-get install -y git
#fi

# Install openstack-installer
cd /root/
if ! [ -f openstack-installer ]; then
    git clone https://github.com/CiscoSystems/openstack-installer.git /root/openstack-installer
fi

